/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package activesdngui;

/**
 *
 * @author mislam7
 */
public class Desktop extends javax.swing.JFrame {

    /**
     * Creates new form Desktop
     */
    public Desktop() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtpMainTabbedPane = new javax.swing.JTabbedPane();
        jpEventSpecification = new javax.swing.JPanel();
        jbCreateEvent = new javax.swing.JButton();
        jpCourseOfAction = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtpMainTabbedPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtpMainTabbedPaneMouseClicked(evt);
            }
        });

        jpEventSpecification.setBackground(new java.awt.Color(204, 204, 204));

        jbCreateEvent.setText("Create Event");

        javax.swing.GroupLayout jpEventSpecificationLayout = new javax.swing.GroupLayout(jpEventSpecification);
        jpEventSpecification.setLayout(jpEventSpecificationLayout);
        jpEventSpecificationLayout.setHorizontalGroup(
            jpEventSpecificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpEventSpecificationLayout.createSequentialGroup()
                .addContainerGap(503, Short.MAX_VALUE)
                .addComponent(jbCreateEvent)
                .addGap(472, 472, 472))
        );
        jpEventSpecificationLayout.setVerticalGroup(
            jpEventSpecificationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpEventSpecificationLayout.createSequentialGroup()
                .addContainerGap(469, Short.MAX_VALUE)
                .addComponent(jbCreateEvent)
                .addGap(183, 183, 183))
        );

        jtpMainTabbedPane.addTab("Event", jpEventSpecification);

        javax.swing.GroupLayout jpCourseOfActionLayout = new javax.swing.GroupLayout(jpCourseOfAction);
        jpCourseOfAction.setLayout(jpCourseOfActionLayout);
        jpCourseOfActionLayout.setHorizontalGroup(
            jpCourseOfActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1097, Short.MAX_VALUE)
        );
        jpCourseOfActionLayout.setVerticalGroup(
            jpCourseOfActionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 681, Short.MAX_VALUE)
        );

        jtpMainTabbedPane.addTab("Action", jpCourseOfAction);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jtpMainTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtpMainTabbedPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtpMainTabbedPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtpMainTabbedPaneMouseClicked
        MainFrame mainFrame = new MainFrame();
        mainFrame.setVisible(true);
        jpEventSpecification.add(mainFrame);
    }//GEN-LAST:event_jtpMainTabbedPaneMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Desktop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbCreateEvent;
    private javax.swing.JPanel jpCourseOfAction;
    private javax.swing.JPanel jpEventSpecification;
    private javax.swing.JTabbedPane jtpMainTabbedPane;
    // End of variables declaration//GEN-END:variables
}
