/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package activesdngui;

import java.util.HashMap;
import javax.swing.BoxLayout;

/**
 *
 * @author Mazharul
 */
public class MainFrame extends javax.swing.JFrame {

    public static MainFrame mainFrame;
    AllEvent allEvtPanel;
    private HashMap<Integer, Event> events = new HashMap<>();
    public MainFrame() {
        initComponents();
        customInit();
    }

    private void customInit() {
        allEvtPanel = new AllEvent();
        CourseOfAction courseOfAction = new CourseOfAction();
//        jtpMainTabbedPan.addTab("Event", allEvtPanel);
//        jtpMainTabbedPan.addTab("Course of Action", courseOfAction);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtpMainTabbedPan = new javax.swing.JTabbedPane();
        jpEventSpecificationHolder = new javax.swing.JPanel();
        jpCourseOfActionsHolder = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtpMainTabbedPan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtpMainTabbedPanMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpEventSpecificationHolderLayout = new javax.swing.GroupLayout(jpEventSpecificationHolder);
        jpEventSpecificationHolder.setLayout(jpEventSpecificationHolderLayout);
        jpEventSpecificationHolderLayout.setHorizontalGroup(
            jpEventSpecificationHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1155, Short.MAX_VALUE)
        );
        jpEventSpecificationHolderLayout.setVerticalGroup(
            jpEventSpecificationHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );

        jtpMainTabbedPan.addTab("Event Specification", jpEventSpecificationHolder);

        javax.swing.GroupLayout jpCourseOfActionsHolderLayout = new javax.swing.GroupLayout(jpCourseOfActionsHolder);
        jpCourseOfActionsHolder.setLayout(jpCourseOfActionsHolderLayout);
        jpCourseOfActionsHolderLayout.setHorizontalGroup(
            jpCourseOfActionsHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1155, Short.MAX_VALUE)
        );
        jpCourseOfActionsHolderLayout.setVerticalGroup(
            jpCourseOfActionsHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );

        jtpMainTabbedPan.addTab("Course of Actions", jpCourseOfActionsHolder);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtpMainTabbedPan))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtpMainTabbedPan))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtpMainTabbedPanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtpMainTabbedPanMouseClicked
        jpEventSpecificationHolder.removeAll();
        jpEventSpecificationHolder.setLayout(new BoxLayout(jpEventSpecificationHolder, BoxLayout.X_AXIS));
        jpEventSpecificationHolder.add(allEvtPanel);
        jpEventSpecificationHolder.revalidate();
        jpEventSpecificationHolder.repaint();
    }//GEN-LAST:event_jtpMainTabbedPanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            mainFrame = new MainFrame();
            mainFrame.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jpCourseOfActionsHolder;
    private javax.swing.JPanel jpEventSpecificationHolder;
    private javax.swing.JTabbedPane jtpMainTabbedPan;
    // End of variables declaration//GEN-END:variables
}
