/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package activesdngui;

import java.util.HashMap;
import javax.swing.BoxLayout;

/**
 *
 * @author Mazharul
 */
public class MainFrame extends javax.swing.JFrame {

    public static MainFrame mainFrame;
    public static AllEvent allEvtPanel;
    public static About about;
    public static CourseOfAction courseOfAction;
    private HashMap<Integer, Event> events = new HashMap<>();

    public MainFrame() {
        initComponents();
        customInit();
    }

    private void customInit() {
        allEvtPanel = new AllEvent();
        about = new About();
        courseOfAction = new CourseOfAction();
//        jtpMainTabbedPan.addTab("Event", allEvtPanel);
//        jtpMainTabbedPan.addTab("Course of Action", courseOfAction);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpPolicyHolder = new javax.swing.JPanel();
        jmbMainMenu = new javax.swing.JMenuBar();
        jmPolicy = new javax.swing.JMenu();
        jmiEventSpecification = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmiCourseOfActions = new javax.swing.JMenuItem();
        jmAbout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jpPolicyHolderLayout = new javax.swing.GroupLayout(jpPolicyHolder);
        jpPolicyHolder.setLayout(jpPolicyHolderLayout);
        jpPolicyHolderLayout.setHorizontalGroup(
            jpPolicyHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1182, Short.MAX_VALUE)
        );
        jpPolicyHolderLayout.setVerticalGroup(
            jpPolicyHolderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 605, Short.MAX_VALUE)
        );

        jmPolicy.setText("Policy");

        jmiEventSpecification.setText("Event Specification");
        jmiEventSpecification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEventSpecificationActionPerformed(evt);
            }
        });
        jmPolicy.add(jmiEventSpecification);
        jmPolicy.add(jSeparator1);

        jmiCourseOfActions.setText("Course of Actions");
        jmiCourseOfActions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCourseOfActionsActionPerformed(evt);
            }
        });
        jmPolicy.add(jmiCourseOfActions);

        jmbMainMenu.add(jmPolicy);

        jmAbout.setText("About");
        jmAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmAboutMouseClicked(evt);
            }
        });
        jmbMainMenu.add(jmAbout);

        setJMenuBar(jmbMainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPolicyHolder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpPolicyHolder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiEventSpecificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEventSpecificationActionPerformed
        jpPolicyHolder.removeAll();
        jpPolicyHolder.setLayout(new BoxLayout(jpPolicyHolder, BoxLayout.X_AXIS));
        jpPolicyHolder.add(allEvtPanel);
        jpPolicyHolder.revalidate();
        jpPolicyHolder.repaint();
    }//GEN-LAST:event_jmiEventSpecificationActionPerformed

    private void jmAboutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmAboutMouseClicked
        jpPolicyHolder.removeAll();
        jpPolicyHolder.setLayout(new BoxLayout(jpPolicyHolder, BoxLayout.X_AXIS));
        jpPolicyHolder.add(about);
        jpPolicyHolder.revalidate();
        jpPolicyHolder.repaint();
    }//GEN-LAST:event_jmAboutMouseClicked

    private void jmiCourseOfActionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCourseOfActionsActionPerformed
        jpPolicyHolder.removeAll();
        jpPolicyHolder.setLayout(new BoxLayout(jpPolicyHolder, BoxLayout.X_AXIS));
        jpPolicyHolder.add(courseOfAction);
        jpPolicyHolder.revalidate();
        jpPolicyHolder.repaint();
    }//GEN-LAST:event_jmiCourseOfActionsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            mainFrame = new MainFrame();
            mainFrame.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu jmAbout;
    private javax.swing.JMenu jmPolicy;
    private javax.swing.JMenuBar jmbMainMenu;
    private javax.swing.JMenuItem jmiCourseOfActions;
    private javax.swing.JMenuItem jmiEventSpecification;
    private javax.swing.JPanel jpPolicyHolder;
    // End of variables declaration//GEN-END:variables
}
