/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package activesdngui.views.actionviews;

import activesdngui.model.GenericSignaturePanel;
import activesdngui.model.Signature;
import java.util.HashMap;
import javax.swing.JTextField;

/**
 *
 * @author mislam7
 */
public class ProtocolCheckerView extends GenericSignaturePanel {

    public static final String SIG_NAME = "UDP ICMP Checker";
    public static final String RATE = "Rate";
    
    /**
     * Creates new form ElephantCheckerView
     */
    public ProtocolCheckerView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfRate = new javax.swing.JTextField();

        jLabel1.setText("Rate (in %)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jtfRate, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(253, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jtfRate;
    // End of variables declaration//GEN-END:variables

    public JTextField getJtfRate() {
        return jtfRate;
    }

    public void setJtfRate(JTextField jtfRate) {
        this.jtfRate = jtfRate;
    }

    @Override
    public Signature parseData() {
        Signature signature = new Signature(SIG_NAME, Signature.UDP_ICMP_CHECKER_ID);

        HashMap<String, Object> fields = signature.getFields();
        fields.put(RATE, jtfRate.getText());
        
        return signature;
    }

    @Override
    public void loadData(Signature signature) {
        if (signature != null) {
            HashMap<String, Object> fields = signature.getFields();
            jtfRate.setText((String) fields.get(RATE));
        }
    }

    @Override
    public Integer getSignatureId() {
        return Signature.UDP_ICMP_CHECKER_ID;
    }

}
